apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: test
  namespace: default
spec:
  type: generic
  address: https://webhook.site/a23efe4d-3768-4cea-a800-b3a8aeee5f69