apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: test
  namespace: default
spec:
  type: generic
  address: https://webhook.site/6d35e1a2-d2a0-4b4a-981d-9046d3e7fa6a
