apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: flux-system
  path: ./resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: test
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: test
      namespace: flux-system
  timeout: 1m