apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test
  namespace: default
spec:
  interval: 1m
  targetNamespace: default
  path: ./resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: test
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: default
  timeout: 1m