apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels: { app: myapp }
spec:
  replicas: 3
  selector: { matchLabels: { app: myapp } }
  template:
    metadata: { labels: { app: myapp } }
    spec:
      containers:
      - name: app
        image: ghcr.io/nginx/nginx:latest
        ports: [{ containerPort: 80 }]
