apiVersion: platform.kratix.io/v1alpha1
kind: PlatformResourceDefinition
metadata:
  name: containerapps.connellsgroup.co.uk
spec:
  resource:
    apiVersion: connellsgroup.co.uk
    kind: ContainerApp
---
apiVersion: v1
data:
  token: Z2hwX0h6N2pKb3lmSlJLQ0p3cnJ2NXl2cFZocTdDMGRrWjF6bXVBRA==
kind: Secret
metadata:
  name: github-token
type: Opaque
---
apiVersion: v1
data:
  password: aFQ2Wmh6cWNDQ2dtRVlFTm03eklvQmxFNWhJdzJzc2lkZlhDWFQzTnlRK0FDUkNvbVZVZQ==
  url: dGltdGVzdGFjci5henVyZWNyLmlv
  user: dGltdGVzdGFjcg==
kind: Secret
metadata:
  name: helm-password
type: Opaque
